# 1. Data Understanding

## Import Required Libraries and Dataset

In [1]:
# Import required libraries
import pandas as pd

In [2]:
#Import dataset
df = pd.read_csv('../Data/processed.cleveland.data', header = None)

In [3]:
#Preview dataset - confirm dataset has been read correctly
df.head()

     0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0

In [4]:
#Rename Columns - Using 'heart-disease.names' file provided by UCI
columns = [
    'age',
    'sex',
    'cp',
    'trestbps',
    'chol',
    'fbs',
    'restecg',
    'thalach',
    'exang',
    'oldpeak',
    'slope',
    'ca',
    'thal',
    'target'
]

df.columns = columns

#Check columns have been names properly
df.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2

## Data Dictionary

|Name|Description|Encoding|Role|
|----|-----------|--------|-----|
|age|age of patient in years|N/A|Feature|
|sex|sex of patient (M/F)|1.0 = Male; 0.0 = Female|Feature|
|cp|type of chest pain|1 = typical angina; 2 = atypical angina; 3 = non-anginal pain; 4 = asymptomatic|Feature|
|trestbps|resting blood pressure when admitted to hospital (mmHg)|N/A|Feature|
|chol| serum cholesterol (mg/dl)|N/A|Feature|
|fbs|fasting blood sugar > 120 mg/dl|1 = True; 0 = False|Feature|
|restecg|results from resting electrocardiograph| 0 = normal; 1 = ST-T wave abnormality (T wave inversions/ST elevation or depression > 0.05 mV); 2 = possible/definite left ventricular hypertrophy|Feature|
|thalach|maximum heart rate achieved during exercise (bpm)|N/A|Feature|
|exang|exercise induced angina|1 = yes; 0 = no|Feature|
|oldpeak|ST depression caused by exercise relative to rest|N/A|Feature|
|slope|slope of peak exercise ST segment|1 = upsloping; 2 = flat; 3 = downsloping|Feature|
|ca|number of major blood vessels (LAD, LCx, RCA) coloured by fluoroscopy| 0, 1, 2, 3|Feature|
|thal|thalium stress test result|3 = normal; 6 = fixed defect; 7 = reversible defect|Feature|
|target|diagnosis of heart disease (angiographic disease status)| 0 - 4 (0 = no diagnosis; 1-4 = diagnosis with '4' being most severe)|Target|

# Data Structure

In [5]:
#Find the number of rows and columns
df.shape

(303, 14)

In [6]:
#Check the data types of each column
df.dtypes

age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca           object
thal         object
target        int64
dtype: object

**Comments:**
* The dataset has 303 rows and 14 columns
* The dataset is made up of three different data types: float64, object, and int64.
* It may be beneficial to switch columns which are encoded (i.e. 1 = male, 0 = female) into categorical data types as well, including the target variable.

## Summary Statistics

In [7]:
#Get an intital overview of the central tendency and distribution of the data
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000

**Comments:**
* The dataset contains ages from 29 to 77 years old. This is a good distribution for the project goal.
* We can see a varied amount of trestbps and cholesterest levels with min levels of 94 mmHg and 126 mg/dl and max levels of 200 mmHg and 564 mg/dl respectively.
* However, we have a max value of 4.00 in the target column, it might be more appropriate to introduce binary encoding during data cleaning to only suggest the presence/absence of a heart disease diagnosis.

## Check for missing values/duplicated values

In [8]:
#check for missing values (N/As)
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
#Check for blank strings
(df == '').any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [10]:
#Check for duplicated
df.duplicated().sum()

0

**Comments:**
* There is no missing values (N/As or blank strings) and there is also no duplicated values, suggesting there is no need for imputation/removal of rows just yet.

## Check Object Data Types

In [11]:
print(df['thal'].str.isnumeric().all())
print(df['ca'].str.isnumeric().all())

False
False

In [12]:
print(df['thal'].unique())
print(df['ca'].unique())

['6.0' '3.0' '7.0' '?']
['0.0' '3.0' '2.0' '1.0' '?']

In [13]:
print((df == '?').sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

In [14]:
#How much of dataset does rows with "?" represent
thal_missing = (df['thal'] == '?').sum()
print(f'percent of missing value "thal" values: {round(thal_missing/len(df)*100,2)}')

ca_missing = (df['ca'] == '?').sum()
print(f'percent of missing value "ca" values: {round(ca_missing/len(df)*100,2)}')

percent of missing value "thal" values: 0.66
percent of missing value "ca" values: 1.32

**Comments:**
* It has been found that whilst there is no missing values in the dataset ('NA's/blank strings), the columns `ca` and `thal` contain '?'.
* As these rows make up less than 2% (less than industry-standard of 5%) of the dataset each, it is safe to remove them.

## Summary: Data Understanding
* There is currently only 2 data cleaning issues present.
* First, we need to remove the rows which contain '?'. It should not affect modelling as these rows make up for less than 2% of the dataset each.
* Secondly, we need to update the float data types into categorical data types for columns: `sex`, `cp`,`fbs`,`restecg`,`exang`,`slope`,`target` - as these will help with the encoding stages of preprocessing.

# 2. Data Cleaning
I decided to carry out data cleaning before EDA for this particular dataset as most columns were categorical data but represented as a float. Therefore, I converted these columns in order to aid in smoother analysis during EDA.

### Removal of rows with missing values

In [15]:
#As we know '?' is only in 'thal' and 'ca' columns can subset the dataframe to exclude these
df = df[(df['ca'] != '?') & (df['thal'] != '?')]

#Check this worked
print((df == '?').sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Change Encoded Columns to Categorical Data Types

In [16]:
#Change 'thal' and 'ca' to numeric columns as they were already strings
#Do this so they are able to be converted into integers (easier for preprocessing step)
df[['thal','ca']] = df[['thal','ca']].apply(pd.to_numeric)

#Turn encoded columns into 'object' data type
update_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal', 'ca', 'target']
df[update_cols] = df[update_cols].astype('Int64')
df[update_cols] =  df[update_cols].astype('object')

#Check that this has worked
df.dtypes

age         float64
sex          object
cp           object
trestbps    float64
chol        float64
fbs          object
restecg      object
thalach     float64
exang        object
oldpeak     float64
slope        object
ca           object
thal         object
target       object
dtype: object

In [17]:
#Preview data
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,1,145.0,233.0,1,2,150.0,0,2.3,3,0,6,0
1,67.0,1,4,160.0,286.0,0,2,108.0,1,1.5,2,3,3,2
2,67.0,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2,7,1
3,37.0,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0,3,0
4,41.0,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0,3,0

## Summary: Data Cleaning

* First, we removed all rows containing '?' in `thal` and `ca`. The presence of '?' was blocking these columns from conversion into integer format to remove the '.0'.
* we have converted all encoded columns into integers (to get rid of '.0') and then turned them into categorical variables ready for EDA and preprocessing.
* The data is now ready for EDA and preprocessing

In [18]:
#Save cleaned df to folder ready for EDA and preprocessing
df.to_csv('../Data/clean_df.csv', index = False)